-- Temporarily disable RLS for development
ALTER TABLE public.cliente DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.proyecto DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.usuario DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.rol DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.claseorden DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.ordenpedido DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.responsableorden DISABLE ROW LEVEL SECURITY;