// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ldeutwedxmonbdewudyh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxkZXV0d2VkeG1vbmJkZXd1ZHloIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyNDIxNTMsImV4cCI6MjA3MTgxODE1M30.2Dq2o9HRdxxGpUwmsrmaOvN6q1mHd3KkBzEZ3KecRY0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});